{
  "metadata": [
    {
      "newspaper": "akorda_addresses",
      "lang": "ru",
      "save_path": "akorda_addresses_ru/",
      "base_filename": "akorda_addresses_ru_Stage1_",
      "base_url": "https://akorda.kz/ru/addresses?page=",
      "article_base_url": "https://akorda.kz",
      "default_start_date": "1997-10-16",
      "sitemaps": []
    },
    {
      "newspaper": "akorda_addresses",
      "lang": "en",
      "save_path": "akorda_addresses_en/",
      "base_filename": "akorda_addresses_en_Stage1_",
      "base_url": "https://akorda.kz/en/addresses?page=",
      "article_base_url": "https://akorda.kz",
      "default_start_date": "1997-10-16",
      "sitemaps": []
    },
    {
      "newspaper": "akorda_addresses",
      "lang": "kz",
      "save_path": "akorda_addresses_kz/",
      "base_filename": "akorda_addresses_kz_Stage1_",
      "base_url": "https://akorda.kz/kz/addresses?page=",
      "article_base_url": "https://akorda.kz",
      "default_start_date": "1997-10-16",
      "sitemaps": []
    }
  ]
}