{
  "metadata": [
    {
      "newspaper": "akorda_legal_acts",
      "lang": "ru",
      "save_path": "akorda_legal_acts_ru/",
      "base_filename": "akorda_legal_acts_ru_Stage1_",
      "base_url": "https://akorda.kz/ru/legal_acts?page=",
      "article_base_url": "https://akorda.kz",
      "default_start_date": "2012-04-09",
      "sitemaps": []
    },
    {
      "newspaper": "akorda_legal_acts",
      "lang": "en",
      "save_path": "akorda_legal_acts_en/",
      "base_filename": "akorda_legal_acts_en_Stage1_",
      "base_url": "https://akorda.kz/en/legal_acts?page=",
      "article_base_url": "https://akorda.kz",
      "default_start_date": "2012-03-01",
      "sitemaps": []
    },
    {
      "newspaper": "akorda_legal_acts",
      "lang": "kz",
      "save_path": "akorda_legal_acts_kz/",
      "base_filename": "akorda_legal_acts_kz_Stage1_",
      "base_url": "https://akorda.kz/kz/legal_acts?page=",
      "article_base_url": "https://akorda.kz",
      "default_start_date": "2012-04-12",
      "sitemaps": []
    }
  ]
}